### ISSUE TITLE
Offer to Typelevel?

### ISSUE THREAD

**Issue by rossabaker** [typelevel/jawn-fs2#106]
Proposal: move this project to Typelevel GitHub org and `org.typelevel` Maven org

Pros:
- This library has nothing to do with HTTP
- Perhaps gets more attention in Typelevel
- It integrates two Typelevel libraries, including one hosted by Typelevel

Cons:
- We'd want to change the package when we change the organization.
- It's not broken

Compromise:
- Make it a Typelevel project, but keep it here

**Comment by aeons** [comment]
Yes, to moving both repo and org.

**Comment by ChristopherDavenport** [comment]
All work, and the sooner we make a decision the better.

**Comment by rossabaker** [comment]
https://github.com/http4s/jawn-fs2/issues/106

**Comment by rossabaker** [comment]
Okay, approved and transferred.  We need to repackage and republish, but it's found its home.
